### ISSUE TITLE
分类问题也是用MSE_loss吗？

### ISSUE THREAD

**Issue by feynmanyunlongma** [ruizhang-ai/SIGN-Detecting-Beneficial-Feature-Interactions-for-Recommender-Systems#1]
1. 从论文以及代码上看，分类问题也是用MSE_loss，请问我理解的对吗，如果是的话，为什么要这样用呢？

2. 边的权重f_ep，我理解通过L0近似方法得到的是 0 <= s <=1，为什么case study里有负的权重呢？

谢谢~

**Comment by suyixin12123** [comment]
您好，

1. 我们的模型没有特殊的loss方法的要求，您也可以尝试其他的loss方法。
2. case study中的权重是interaction modeling的结果（通过function h）。而f_ep得到的是边是否相连的信息，即有没有interaction。
